---
title: "Readme.Rmd"
author: "suszanna"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

File:          Readme.md
Lesson:        project for lesson4
Certification: Data Science Specialization 
From:          Johns Hopkins University, 
Sponsored by:  Coursera.

Lesson4 - course project in analysis of dataset in R

course:  Getting and Cleaning data
student: Susan Martin

files included here: 
   readme.Rmd  .. orientation\
   cd_book.txt .. codebook to list variables of interest found in 
   run_analysis.R .. R code to parse data set for mean values
   Get_clean.txt .. output file from execution of run_analysis.R
  
Steps coded to get and clean data:

1 Merge the training and the test sets to create one data set.
2 Extracts only the measurements on the mean and standard deviation for each measurement.
3 Uses descriptive activity names to name the activities in the data set
4 Appropriately label the data set with descriptive variable names
5 From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
